import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./styles/main.scss";

// Google font: Albert Sans
const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

// Local font: Neue Montreal
const neueMontreal = localFont({
  variable: "--font-neue-montreal",
  display: "swap",
  src: [

  ],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={${.variable} ${.variable} antialiased}
      >
        {children}
      </body>
    </html>
  );
}